routes/web.php
<?php
use App\Usuario;
use Illuminate\Support\Facades\Route;



Route::get('/', function () {
 return view('usuarios.inicio');
});

Route::resource('Usuario','UsuarioController');
Route::resource('Perfil','PerfilController');

app/Perfil.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Perfil extends Model
{
    protected $connection = 'oracle';
    protected $table = 'perfil';
    protected $fillable = [
        'cd_perfil','ds_perfil','ie_situacao','dt_atauzalicao'

    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Usuario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Usuario extends Model
{ 
    protected $connection = 'mysql';
    protected $fillable = [
        'nome', 'email'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PerfilController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Perfil;
use  Illuminate\Database\Eloquent\Collection;

class PerfilController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        //$perfil=DB::table('perfil')->get(); //Não entendi o motivo de esta chamando o DB. Pra que a Model então?
        $perfil=Perfil::paginate(15);;
        /*$perfil=Perfil::all()->paginate(15);*/


            //return view('usuarios.perfil', [
                //'perfil' => DB::table('perfil')->paginate(50);//Não entendi o motivo de esta chamando o DB. Pra que a Model então?
                //'perfil' => $perfil, //Não precisava fazer a mesma consulta 2 vezes
            //]);


            return view("usuarios.perfil", compact("perfil")); //Você pode chamar a view com o uso do "compact".
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/UsuarioController.php
<?php
namespace App\Http\Controllers;
use App\Http\Requests\StoreUpdateUsuarioRequest;
use App\Usuario;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;


/**
 * identar código é importante!
 */
class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $usuario;
    public function __construct(Usuario $usuario){
$this ->usuario = $usuario;

    }
    public function index()
         
    {
       //estude sobre o seguinte assunto: injeção de dependência
       $usuarios = $this ->usuario->all();
       return view('usuarios.index', compact('usuarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('usuarios.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\StoreUpdateUsuarioRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUpdateUsuarioRequest $request)
    {

        try {
            //estude sobre o seguinte assunto: injeção de dependência
            $usuario = new Usuario();
            $usuario->nome = $request->nome;
            $usuario->email = $request->email;
            $usuario->save();

            $usuarios = Usuario::all();
            Flash('Usuario Cadastrado com sucesso!!!')->success();
            return view('usuarios.index', compact('usuarios'));
        } catch (\Throwable $th) {
            //Não entendi o motivo de qualquer erro ser "email já cadastrado".
            //Faça consistências dentro da Request!!!
            Flash('Ops!! Ocorreu um erro')->error();
            return redirect()->route('Usuario.index');
        

        
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            //estude sobre o seguinte assunto: injeção de dependência
            $usuario = Usuario::findOrFail($id);
            return view('usuarios.delete', compact('usuario'));
        } catch (\Exception $e) {

            $usuarios = Usuario::all();
            Flash('Ops!!. Ocorreu um erro O Usuário não Existe')->error();
           //return view('usuarios.create');
            //O ideal é você utilizar rotas já existentes!
            //return view('usuarios.index', compact('usuarios'));
            return redirect()->route('Usuario.index');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      try {
        $usuario = Usuario::findOrFail($id);
        return view('usuarios.edit', compact('usuario'));
      } catch (\Throwable $th) {
              Flash('Ops!! Não é possivel editar Usuario não existe')->error();
        return redirect()->route('Usuario.index');
      }

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  App\Http\Requests\StoreUpdateUsuarioRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUpdateUsuarioRequest $request, $id)
    {
    try {
        //estude sobre o seguinte assunto: injeção de dependência
        $usuario = Usuario::findOrFail($id);
        $usuario->nome = $request->nome;
        $usuario->email = $request->email;
        $usuario->save();
      
        Flash('Usuario Atualizado com sucesso!!!')->success();

        return redirect()->route('Usuario.index'); //Usar rotas já existente!!!
        //return view('usuarios.index', compact('usuarios'));
    } catch (\Throwable $th) {
          $usuario = Usuario::findOrFail($id);
          Flash('Ops!! Algo deu errado tente novamente')->error();
          return view('usuarios.edit');

    }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            //estude sobre o seguinte assunto: injeção de dependência
            $usuario = Usuario::findOrFail($id);
            $usuario ->delete();

            $usuarios = Usuario::all();
            Flash('Usuario Deletado com sucesso!!!')->warning();
            return view('usuarios.index', compact('usuarios'));
        } catch (\Throwable $th) {
            $usuarios = Usuario::all();
            return redirect()->route('Usuario.index');
        }
    }
}

resources/views/usuarios/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
   <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    @stack('styles')
</head>
<body>

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{{url('/')}}">Inicio</span></a>
                <a class="nav-item nav-link" href="{{route('Perfil.index')}}">Perfil</a>
                <a class="nav-item nav-link" href="{{route('Usuario.index')}}">Usuarios</a>
              </div>
            </div>
          </nav>
    @yield('content')        
</div>
</body>
</html>

resources/views/usuarios/create.blade.php
@extends('usuarios.app')
@section('title','Cadastro')
@section('content')
@include('flash::message')

@if($errors->any())
<div>
    <ul>
    @foreach ($errors->all() as $messagem)
    <li>{{$messagem}}</li>
    @endforeach
    </ul>
</div>   
@endif    
<h1 class="text-center">Criar um novo Usuario</h1>
<div id="criar">
 
    <form action="{{route('Usuario.store')}}" method="POST">
      @csrf
         <div class="col-form-label">
          <label for="exampleInputEmail1" class="form-label">Nome</label>
          <br>
          <input type="text" class="col-auto" id="label" name="nome">
          <div id="emailHelp" class="form-text"></div>
        </div>
        <div class="col-form-label">
          <label  for="exampleInputPassword1" class="form-label">Email</label>
          <br>
          <input type="email" class="col-auto" id="label" name="email">
        </div>
        
        <button type="submit" class="btn btn-primary">Cadastrar</button>
      </form>

    </div>
    @endsection 

resources/views/usuarios/edit.blade.php
@extends('usuarios.app')

@section('title','Editar Produtos')
@section('content')
    
@include('flash::message')
    @if($errors->any())
<div class = "alert alert-danger">
    <ul>
    @foreach ($errors->all() as $messagem)
    <li>{{$messagem}}</li>
    @endforeach
    </ul>
</div>   
@endif    
    <h1 class="text-center">editar Usuario</h1>
<div id ="criar">
    <form action="{{route('Usuario.update',$usuario->id)}}" method="post">
        @method('PUT')
        @CSRF
        <div class="col-form-label">
            <label for="exampleInputEmail1" class="form-label">Nome</label>
            <br>
            <input type="text" class="col-auto" id="label" name="nome" value="{{$usuario->nome}}">
            <div id="emailHelp" class="form-text"></div>
          </div>
          <div class="col-form-label">
            <label  for="exampleInputPassword1" class="form-label">Email</label>
            <br>
            <input type="email" class="col-auto" id="label" name="email" value="{{$usuario->nome}}">
            <br>
        <button class="btn btn-primary">Editar</button>
        
    </div>
    </form>
    @endsection

resources/views/usuarios/index.blade.php
@extends('usuarios.app')   
@section('title','Usuarios')
@section('content')


<h1 class = 'text-center'>Usuarios</h1>
    <a href="{{route('Usuario.create')}}" class ='btn btn-success my-2' >Novo+</a>
    
    @include('flash::message')
   
    <table class="table table-striped table-hover ">

        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Email</th>
                <th width = '200'>Ações</th>
               
            </tr>
        </thead>
        <tbody>
        @foreach($usuarios as $usuario)
            <tr>
                <th>{{$usuario->id}}</th>
                <th>{{$usuario->nome}}</th>
                <th>{{$usuario->email}}</th>

                
                

                <th>
                    <form action="{{route('Usuario.destroy',$usuario->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <a href="{{route('Usuario.edit',$usuario->id)}}" class="btn btn-primary">Editar</a>
                    <button type="submit"  class="btn btn-danger">Excluir</button>
                    </form>
                </th>

            </tr>

        @endforeach
        </tbody>
    </table>
    @endsection

resources/views/usuarios/inicio.blade.php
@extends('usuarios.app')
@section('title','Inicio')
@section('content')
    <h1 class="text-center">Desafio Crud</h1>
@endsection

resources/views/usuarios/perfil.blade.php
@extends('usuarios.app')   
@section('title','Perfil')
@section('content')
    

<h1 class = 'text-center'>Perfis Cadastrados no Tasy</h1>
    @include('flash::message')
   
    <table class="table table-striped table-hover ">

        <thead>
            <tr>
                <th>Cod.Perfil</th>
                <th>Perfil</th>
                <th>status</th>
               
            </tr>
        </thead>
        <tbody>
        @foreach($perfil as $perfils)
            <tr>
                <th>{{$perfils->cd_perfil}}</th>
                <th>{{$perfils->ds_perfil}}</th>
                <th>{{$perfils->ie_situacao}}</th>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $perfil->links() }}
    @endsection